### PR TITLE
Update rust version to stop build failures.

### PR DESCRIPTION
**Pull request by jlb6740**

### CODE REVIEW

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Thanks! Seems there's also a compile error somewhere:

```
 DEBUG sightglass_artifact::docker > error[E0599]: no function or associated item named `from_binary` found for struct `wasmtime::Module` in the current scope
 DEBUG sightglass_artifact::docker >    --> crates/bench-api/src/lib.rs:457:30
 DEBUG sightglass_artifact::docker >     |
 DEBUG sightglass_artifact::docker > 457 |         let module = Module::from_binary(self.linker.engine(), bytes)?;
 DEBUG sightglass_artifact::docker >     |                              ^^^^^^^^^^^ function or associated item not found in `wasmtime::Module`
```

Another step seems to be using an even older version of Rust that breaks `bitflags!`, as seen in https://github.com/bytecodealliance/sightglass/pull/148/checks?check_run_id=3458213282#step:4:3474: `Step 1/7 : FROM rust:1.45`. Can you change this one too please?

**Comment by fitzgen** [comment]
Merged https://github.com/bytecodealliance/wasmtime/pull/3261 and restarted all these CI jobs.

**Review by fitzgen — APPROVED** [review]

**Comment by jlb6740** [comment]
```
Error: Invalid name type (at offset 1782373)
Error: Process completed with exit code 1.
```

Hi @fitzgen @bnjbvr, I'm not familiar with this CI error above and I do not know how to tell what is causing it. Any pointers?

**Comment by fitzgen** [comment]
It sort of looks like a `wasmparser` error, not sure what's going on here. Do we try to parse the rebuilt wasm files to make sure they are actually wasm files? I'd add some logging in the rebuild script to shine some more light on the context where this error is cropping up.

**Comment by jlb6740** [comment]
> It sort of looks like a `wasmparser` error, not sure what's going on here. Do we try to parse the rebuilt wasm files to make sure they are actually wasm files? I'd add some logging in the rebuild script to shine some more light on the context where this error is cropping up.

Thanks I see how to debug now and can reproduce the error locally. Looks like wasmprinter needs an update in one of the tomls.
